# -*- coding: utf-8 -*-
"""task1_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUGM8z6iRAaTYXt2O41REUnEE-4O8C4O
"""

#Load the dataset
import pandas as pd

df = pd.read_csv('netflix_titles.csv')
df.head()

#Check for Null Values
df.isnull().sum()

#fill the missing value
df.dropna(subset=['director', 'cast'], inplace=True)
df['rating'].fillna('Not Rated', inplace=True)

#Remove the duplicates
df.drop_duplicates(inplace=True)

#Standardize Text
df['type'] = df['type'].str.lower().str.strip()
df['country'] = df['country'].str.strip()

#Fix Date Format
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

#Rename Columns
df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]

# Fix Data Types
df['release_year'] = df['release_year'].astype(int)

import pandas as pd

# Assuming 'df' is your DataFrame

# Replace missing values in all columns with 'Unknown'
df = df.fillna('Unknown')

import pandas as pd

# Assuming 'df' is your cleaned DataFrame

# Save the DataFrame to a CSV file named 'netflix_cleaned.csv'
df.to_csv('netflix_cleaned.csv', index=False)

import pandas as pd

# Load the cleaned DataFrame
df = pd.read_csv('netflix_cleaned.csv')

# Check for empty strings and missing values
blank_boxes_found = df.isin(['', ' ', pd.NA, None]).any().any()

if blank_boxes_found:
    print("Blank boxes found in the cleaned DataFrame.")
    # Optional: Identify columns with blank boxes
    blank_box_columns = df.columns[df.isin(['', ' ', pd.NA, None]).any()]
    print("Columns with blank boxes:", blank_box_columns.tolist())
else:
    print("No blank boxes found in the cleaned DataFrame.")

import seaborn as sns
import matplotlib.pyplot as plt


import seaborn as sns
import matplotlib.pyplot as plt

# Type of content on Netflix
sns.countplot(data=df, x='type')
plt.title('Type of Content on Netflix')
plt.show()

# Top 10 countries producing Netflix content
df['country'].value_counts().head(10).plot(kind='barh', color='skyblue')
plt.title('Top 10 Countries by Content')
plt.xlabel('Number of Shows')
plt.show()

# Visualize to Detect Outliers
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['release_year'])
plt.show()